[metadata]
  name = "rust-cross-versions-{{ or $.Env.GitReference "-" }}"

[global]
  plan = "libp2p/ping"
  case = "ping"
  builder = "docker:generic"
  runner = "local:docker"
  concurrent_builds = 1

  [global.build_config]
    path = "./rust/"

{{ with (load_resource "./rust.toml" ) }}
  {{ range .groups }}
    [[groups]]
    id = "{{ .Id }}"
    instances = { count = 1 }

    [groups.build_config.build_args]
      CARGO_FEATURES = '{{ .CargoFeatures }}'
      RUN_ID = '{{ or $.Env.RunId "-" }}'
      RUST_LIBP2P_MASTER_SHA = '{{ or $.Env.RustLibp2pMasterSha "-" }}'
  {{ end }}

  {{ with .master }}
    [[groups]]
    id = "master"
    instances = { count = 1 }

    [groups.build_config.build_args]
      CARGO_FEATURES = '{{ .CargoFeatures }}'
      RUN_ID = '{{ or $.Env.RunId "-" }}'
      RUST_LIBP2P_MASTER_SHA = '{{ or $.Env.RustLibp2pMasterSha "-" }}'
  {{ end }}

  {{ if $.Env.GitReference }}
    {{ with .custom }}
      [[groups]]
      id = "custom"
      instances = { count = 1 }

      [groups.build_config.build_args]
        CARGO_FEATURES = '{{ .CargoFeatures }}'
        CARGO_REMOVE = '{{ .CargoFeatures }}'
        CARGO_PATCH = """
          {{ .CargoFeatures }} = {package = "libp2p", git = "https://{{ or $.Env.GitTarget "github.com/libp2p/rust-libp2p" }}", rev = "{{ $.Env.GitReference }}", default_features = false, features = [ "websocket", "mplex", "yamux", "tcp-async-io", "ping", "noise", "dns-async-std" ], version = "{{ .Version }}", optional = true}
          """
        RUN_ID = '{{ or $.Env.RunId "-" }}'
        RUST_LIBP2P_MASTER_SHA = '{{ or $.Env.RustLibp2pMasterSha "-" }}'
    {{ end }}
  {{ end }}
{{ end }}
