name = "compatibility-go"

[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "tcp-connect"
instances = { min = 2, max = 2, default = 2 }
