name = "compatibility-go"

[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[builders."docker:generic".build_args]
build_image = "golang:1.17-buster" # NOTE: build image vs build base image
run_image = "scratch"

[builders."docker:go"]
enabled = true
build_base_image = "golang:1.17-buster"
# go_proxy_url = "https://goproxy.io"
# go_proxy_mode = "direct"

[runners."local:docker"]
enabled = true

[[testcases]]
name = "tcp-connect"
instances = { min = 2, max = 42, default = 2 }
