name: start testground
description: setup a local testground instance

runs:
  using: "composite"
  steps:
    - name: Checkout testground
      uses: actions/checkout@v2
      with:
        path: testground
        repository: testground/testground

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.17.x"

    - name: Install testground
      shell: bash
      run: make install
      working-directory: testground

    - name: Run testground daemon
      shell: bash
      run: testground daemon > output.log 2>&1 &
