name: start testground
description: setup a local testground instance

runs:
  using: "composite"
  steps:
    # With a raw CP ~= Binary distribution
    - name: Inject testground into PATH
      shell: bash
      run: mkdir ${PWD}/my-bin && echo ${PWD}/my-bin >> $GITHUB_PATH
    - name: pull related images
      shell: bash
      run: docker pull iptestground/sync-service:latest && docker pull iptestground/sidecar:edge
    - name: extract binary (experiment)
      shell: bash
      run: docker cp `docker create lsenta/testground:edge`:/testground "${PWD}/my-bin/testground"
    - name: Run testground daemon
      shell: bash
      run: testground daemon > testground.out 2> testground.err &
    ## Via Docker from Docker.
    # - name: Pull some container in advance
    #   shell: bash
    #   run: docker pull iptestground/testground:edge && docker pull iptestground/sidecar:edge
    # - name: Run testground Docker
    #   shell: bash
    #   run: docker run -d --name=testground-daemon --network=host -v /var/run/docker.sock:/var/run/docker.sock lsenta/testground:edge
    # - name: Extract binary (just an experiment)
    #   shell: bash
    #   run: mkdir -p ${PWD}/my-bin/ && docker cp "testground-daemon:/testground" "${PWD}/my-bin/testground"
    # - name: Inject testground into PATH
    #   shell: bash
    #   run: echo ${PWD}/my-bin >> $GITHUB_PATH
    ## By Building.
    # - name: Checkout testground
    #   uses: actions/checkout@v2
    #   with:
    #     path: testground
    #     repository: testground/testground
    # - name: Setup Go
    #   uses: actions/setup-go@v2
    #   with:
    #     go-version: "1.17.x"
    # - name: Install testground
    #   shell: bash
    #   run: make install
    #   working-directory: testground
    # - name: Run testground daemon
    #   shell: bash
    #   run: testground daemon > output.log 2>&1 &
