name: start testground
description: setup a local testground instance

runs:
  using: "composite"
  steps:
    - name: Checkout testground
      uses: actions/checkout@v2
      with:
        path: testground
        repository: testground/testground

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.16.x"

    - name: Install testground
      run: make install || make install || make install || make install
      working-directory: testground
      shell: bash

    - name: Run the daemon or configure the client
      shell: bash
      run: |
        if [[ ! -z "${TESTGROUND_ENDPOINT}" ]]; then
          mkdir -p ~/testground/;
          cat <<EOF >> ~/testground/.env.toml

          [client]
          endpoint = "${TESTGROUND_ENDPOINT}"
        EOF
        else
          mkdir -p ~/testground/;
          cat <<EOF >> ~/testground/.env.toml

          [daemon.scheduler]
          task_timeout_min          = 60
        EOF
          testground daemon > testground.out 2> testground.err &
        fi;

    - name: Check testground daemon health
      run:
        echo "Waiting for Testground to launch on 8042...";
        while ! nc -z localhost 8042; do
          sleep 1;
        done;
        echo "Testground launched";
        testground healthcheck --runner local:docker --fix;
      shell: bash