[metadata]
  name = "rust-cross-versions {{ .Env.Reference }}"

[global]
  plan = "libp2p/ping-interop/rust"
  case = "ping"
  builder = "docker:generic"
  # total_instances = {{ if .Env.GitReference }}5{{ else }}4{{ end }}
  total_instances = 3
  runner = "local:docker"

[[groups]]
  id = "v0.45.1"
  instances = { count = 1 }

  [groups.build_config.build_args]
    CARGO_FEATURES = 'v045'
    LIBP2P_VERSION = "0.45.1"

[[groups]]
  id = "v0.44.0"
  instances = { count = 1 }

  [groups.build_config.build_args]
    CARGO_FEATURES = 'v044'
    LIBP2P_VERSION = "0.44.0"

[[groups]]
  id = "v0.41.0"
  instances = { count = 1 }

  [groups.build_config.build_args]
    CARGO_FEATURES = 'v041'
    LIBP2P_VERSION = "0.41.0"

# [[groups]]
#   id = "master"
#   instances = { count = 1 }

#   [groups.build]
#     selectors = ['v0.45']

#     [[groups.build.dependencies]]
#       module = "github.com/libp2p/go-libp2p"
#       version = "master"

# {{ if .Env.GitReference }}
# [[groups]]
#   id = "current"
#   instances = { count = 1 }

#   [groups.build]
#     selectors = ['v0.45']

#     [[groups.build.dependencies]]
#       module = "github.com/libp2p/rust-libp2p"
#       version = "{{ .Env.GitReference }}"
# {{ end }}