[metadata]
  name = "quickstart"
  author = "your name here"

[global]
  plan = "compatibility-rust"
  case = "tcp-connect"
  total_instances = 2
  builder = "docker:generic"
  runner = "local:docker"
  disable_metrics = false

[[groups]]
  id = "group1"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.build]
  [groups.run]
    artifact = "compatibility-rust:b8c7078232be"

[[groups]]
  id = "group2"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.build]
  [groups.run]
    artifact = "tg-plan-compatibility-go:7ed26b20d6f9"
