name = "compatibility-rust"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "ping"
instances = { min = 2, max = 10000, default = 5 }
# TODO: pass in other parameters