on:
  workflow_dispatch:
    inputs:
      testground_endpoint:
        type: string
        required: false
        description: testground endpoint
      custom_git_reference:
        type: string
        required: false
        description: go ref
      custom_git_target:
        type: string
        required: false
        description: repository to use as replace target
        default: github.com/libp2p/go-libp2p
  push:
  pull_request:

name: libp2p ping - go test (all) with testground.

jobs:
  run-libp2p-test-plans:
    # If you intend to use this workflow from another repo,
    # you need to pass the repo and the version:
    # uses: "libp2p/test-plans/.github/workflows/run-composition.yml@master"
    uses: "./.github/workflows/run-composition.yml"
    with:
      composition_file: "ping/_compositions/go-cross-versions.toml"
      custom_git_target: ${{ github.event.inputs.custom_git_target }} # nothing or "some-fork/go-libp2p"
      custom_git_reference: ${{ github.event.inputs.custom_git_reference }} # a git branch
      testground_endpoint: ${{ github.event.inputs.testground_endpoint }}
      test_repository: ${{ (github.event.inputs && '') || github.repository }}
      test_ref: ${{ (github.event.inputs && '') || github.event.pull_request.head.sha || github.sha }}
      update_cache: ${{ (github.events.inputs && github.events.update_cache ) || true }}
