name: Run composition file with a custom git reference

on:
  workflow_call:
    inputs:
      dir:
        description: the directory with the testplans DSL test
        required: true
        type: string
jobs:
  run_test:
    name: Run testplans test
    runs-on: ubuntu-latest
    env:
      TEST_PLAN_DIR: ${{ inputs.dir }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          path: test-plans
          repository: ${{ env.TEST_PLAN_REPO }}
          ref: ${{ env.TEST_PLAN_BRANCH }}
      - uses: actions/setup-node@v3
      - run: cd ./test-plans/${{ env.TEST_PLAN_DIR }}
      - uses: ipfs/aegir/actions/cache-node-modules@master
      - name: setup testground
        uses: ./test-plans/.github/actions/setup-testground
      - name: Run the test
        timeout-minutes: 6
        run: npm run test
