name: Test libp2p Compatibility

on:
  workflow_call:
    inputs:
      testsuite:
        required: true
        type: string
      testplan_a:
        required: true
        type: string
      version_a:
        required: true
        type: string
      testplan_b:
        required: true
        type: string
      version_b:
        required: true
        type: string
      testcase:
        required: true
        type: string
jobs:
  run_test:
    name: Run a test with different versions
    runs-on: ubuntu-latest
    env:
      TEST_PLAN_REPO: "laurentsenta/test-plans"
      TEST_PLAN_BRANCH: "compatibility-and-reusable"
      INPUT_TESTSUITE: ${{ inputs.testsuite }}
      INPUT_TESTPLAN_A: ${{ inputs.testplan_a }}
      INPUT_VERSION_A: ${{ inputs.version_a }}
      INPUT_TESTPLAN_B: ${{ inputs.testplan_b }}
      INPUT_VERSION_B: ${{ inputs.version_b }}
      INPUT_TESTCASE: ${{ inputs.testcase }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          path: test-plans
          repository: ${{ env.TEST_PLAN_REPO }}
          ref: ${{ env.TEST_PLAN_BRANCH }}
      - name: setup testground
        uses: ./test-plans/.github/actions/setup-testground
        # TODO: fragile, remove or load from the toml files.
      - name: get our base image in advance
        run: docker pull golang:1.17-buster
      - name: build the test plan
        # TODO: is there a more idiomatic way to do this? Like `with: path: ./test-plans`?
        run: cd ./test-plans/${INPUT_TESTSUITE} && ./build.sh
      - name: run the test plan
        # TODO: same.
        run: cd ./test-plans/${INPUT_TESTSUITE} && ./run.sh
      - name: Setup tmate session on failure
        # TODO: add a timeout.
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
