name: Test libp2p Compatibility

on:
  workflow_call:
    inputs:
      testplan:
        required: true
        type: string
      testcase:
        required: true
        type: string
      rust-ref:
        required: true
        type: string
      go-ref:
        required: true
        type: string
jobs:
  run_test:
    name: Run a test with different rust and go lib versions
    runs-on: ubuntu-latest
    env:
      TEST_PLAN_REPO: "laurentsenta/test-plans"
      TEST_PLAN_BRANCH: "compatibility-and-reusable"
      GO_LIBP2P_REF: ${{ inputs.go-ref }}
      RUST_LIBP2P_REF: ${{ inputs.rust-ref }}
      INPUT_TESTPLAN: ${{ inputs.testplan }}
      INPUT_TESTCASE: ${{ inputs.testcase }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          path: test-plans
          repository: ${{ env.TEST_PLAN_REPO }}
          ref: ${{ env.TEST_PLAN_BRANCH }}
      - name: setup testground
        uses: ./test-plans/.github/actions/setup-testground

      - name: build the test plan
        # TODO: is there a more idiomatic way to do this? Like `with: path: ./test-plans`?
        run: cd ./test-plans && ./build.sh
      - name: run the test plan
        # TODO: same
        run: cd ./test-plans && ./run.sh
